apiVersion: v1
kind: Service
metadata:
  name: convo-api-service
spec:
  selector:
    app: convo-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001